sudo: false

language: go

go: 1.14

before_install:
  - go get github.com/golang/lint/golint

script:
  - go vet ./...
  - $HOME/gopath/bin/golint ./...
  - go test -v ./...

notifications:
  email: false
